import React from 'react';
import { User, Course } from '../../../types';
import { RecommendationEngine } from '../../../services/recommendationService';
import { Sparkles, BookOpen, CheckCircle2 } from 'lucide-react';

interface TraineeRecommendationsViewProps {
  currentUser: User;
  onOpenCourse: (courseId: string) => void;
  onToast: (msg: string) => void;
}

export const TraineeRecommendationsView: React.FC<TraineeRecommendationsViewProps> = ({ currentUser, onOpenCourse, onToast }) => {
  const recommendations = RecommendationEngine.getCourseRecommendations(currentUser);

  return (
    <div className="space-y-6 text-left">
      <div className="bg-white rounded-3xl border border-[#E7E5E4] p-6 sm:p-8 flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-black text-[#0F172A] tracking-tight">Intelligent Recommendations for You</h2>
          <p className="text-xs sm:text-sm text-[#64748B] mt-1">
            Tailored learning paths generated by Capacity AI based on your competency gaps and career progression.
          </p>
        </div>
        <div className="p-3 rounded-2xl bg-[#E8F3F1] text-[#2A7F7E]">
          <Sparkles className="w-8 h-8" />
        </div>
      </div>

      <div className="space-y-6">
        {recommendations.map((rec) => (
          <div key={rec.course.id} className="bg-white rounded-3xl border border-[#E7E5E4] p-6 sm:p-8 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
            <div className="space-y-3 max-w-2xl">
              <div className="flex items-center gap-3">
                <span className="px-3 py-1 rounded-full bg-[#E8F3F1] text-[#2A7F7E] text-xs font-bold font-mono">
                  {rec.matchScore}% Match Score
                </span>
              </div>
              <h3 className="text-xl font-bold text-[#0F172A]">{rec.course.title}</h3>
              <p className="text-xs sm:text-sm text-[#64748B]">{rec.course.description}</p>
              
              <div className="pt-2 space-y-1">
                <p className="text-[11px] font-bold text-[#0D3B66] uppercase font-mono">Why this is recommended:</p>
                {rec.reasons.map((r, i) => (
                  <div key={i} className="flex items-center gap-2 text-xs text-[#57534E]">
                    <CheckCircle2 className="w-4 h-4 text-[#2A7F7E]" />
                    <span>{r.text}</span>
                  </div>
                ))}
              </div>
            </div>

            <button
              onClick={() => onOpenCourse(rec.course.id)}
              className="px-6 py-3 rounded-xl bg-[#0D3B66] text-white text-xs sm:text-sm font-semibold hover:bg-[#092b4d] shrink-0"
            >
              Enroll Now
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
